[hopr]
[hopr.host]
address = ""
port = 0

[hopr.db]
data = "/app/hoprd-db"
initialize = true
force_initialize = false

[hopr.strategy]
on_fail_continue = true
allow_recursive = true
strategies = []

[hopr.chain]
provider = "https://gnosis-rpc.publicnode.com"
network = ""

[hopr.safe_module]
safe_transaction_service_provider = "https://safe-transaction.prod.hoprtech.net/"
safe_address = ""
module_address = ""

[identity]
file = "/app/hopr.id"
password = ""

[api]
enable = true

[api.auth]
token = ""

[api.host]
address = "0.0.0.0"
port = 0
