[meta]
version = "2.0.0"
name = "network2"
network_port_base = 9190
session_port_base = 10100
blokli_url = "https://blokli.hoprnet.org"

[[nodes.mainnet]]
safe_address = "SAFE_ADDRESS"
module_address = "MODULE_ADDRESS"
node_address = "NODE_ADDRESS"
api_password = "API_PASSWORD"
identity_password = "ID_PASSWORD"
identity = "IDENTITY_CONTENT"

[config.hopr.protocol]
outgoing_ticket_price = "200 HOPR"

[[config.hopr.strategy.strategies.ClosureFinalizer]]
max_closure_overdue = "60m"

[env]
RUST_LOG = "info, debug"

[networks.default]
name = "hoprd-network2"
driver = "bridge"
